### ISSUE TITLE
zsync  IP is not logged in audit.log and not in webUI

### ISSUE THREAD

**Issue by d1907** [Zimbra-Community/account-history#10]
zsync  IP is not logged in audit.log and not in webUI

no mobile ip ????

**Comment by ghost** [comment]
Yeah, the problem here is that Zextras Mobile logs in the wrong logfile, aka sync.log where usually a lot of stacktraces are logged as well.

The audit.log where the log should be, does not contain the IP.

I contacted the upstream devs, but they as of yet did not fix it.

See also
https://github.com/Zimbra-Community/account-history/issues/1

I contacted the devs yet again, in the mean time you can and the sync.log to your config, 
https://github.com/Zimbra-Community/account-history#configuring-preferences

It will be a bit ugly, but I will look into a work-around

**Comment by d1907** [comment]
![123](https://user-images.githubusercontent.com/33257203/32233469-8208413a-be6b-11e7-9ea7-758fa5fe5a63.JPG)
added to configuration file config.properties
audit_logs=/opt/zimbra/log/audit.log;/opt/zimbra/log/sync.log

It began to open long
But still there is no IP (((

**Comment by d1907** [comment]
The difference in the log file is only 
  webclient     oip=11.1.1.1
 mobile (zsync)    ip=11.1.1.1

**Comment by ghost** [comment]
you have no oip, check https://github.com/Zimbra-Community/account-history#log-external-ip

**Comment by d1907** [comment]
zimbra@mail:/$ zmlocalconfig zimbra_http_originating_ip_header
zimbra_http_originating_ip_header = X-Forwarded-For
zimbra@mail:/$ 
# cat /opt/zimbra/log/audit.log
/service/soap/AuthRequest] [name=surikovm@xxxxxxx;oip=x.x.x.x;ua=zclient/8.7.11_GA_1854;] security - cmd=Auth; account=

Microsoft-Server-ActiveSync?User=shatrova&DeviceId=ApplF18K9J4VDTWF&DeviceType=iPhone&Cmd=Ping] [ip=x/x/x/x;] security - cmd=Auth

**Comment by ghost** [comment]
ip = should be an internal ip (without proxy, not supported)
oip = should be an external ip (ip passed from proxxy)

Yah, that is a the bug in zextras.... I ask again if the devs are going to fix it, otherwise I will create a work-around tomorrow

**Comment by ghost** [comment]
Added support for reading `protocol` from sync.log
![new](https://user-images.githubusercontent.com/4353213/32374019-577f3b84-c09c-11e7-8765-d6b5a894a947.png)
