### ISSUE TITLE
Zimlet not listed in admin list in 8.8.8

### ISSUE THREAD

**Issue by jbnance** [Zimbra-Community/account-history#15]
Hello,

I just installed this Zimlet on 8.8.8 from master.  The Zimlet is active for users, however, in the admin interface when I browse to "Configure" -> "Zimlets" it is not listed as an installed Zimlet.  The admin extension **is** listed (in "Configure" -> "Admin Extensions"), though without a "Display Name".

**Comment by ghost** [comment]
Yes, because it is deployed in development mode.

You can zip the contents (not the folder) of 
/opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_account_history
to a zip file named: tk_barrydegraaff_account_history.zip

Then rm -Rf tk_barrydegraaff_account_history

and deploy the zip as usual.

We have no translations, and as such, there is no display name.
